import ReactDOM from 'react-dom/client'
import { restaurants } from "/materials/mock"

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
  <div>
    <div>
      <h1>{restaurants[0].name}</h1>
      <h3>Меню</h3>
      <ul>
        <li>
          {restaurants[0].menu[0].name}
          {restaurants[0].menu[0].price}
          {restaurants[0].menu[0].ingredients}
        </li>
        <li>
          {restaurants[0].menu[1].name}
          {restaurants[0].menu[1].price}
          {restaurants[0].menu[1].ingredients}
        </li>
        <li>
          {restaurants[0].menu[2].name}
          {restaurants[0].menu[2].price}
          {restaurants[0].menu[2].ingredients}
        </li>
      </ul>
      <h3>Отзывы</h3><ul>
        <li>
          {restaurants[0].reviews[0].user}
          {restaurants[0].reviews[0].text}
          {restaurants[0].reviews[0].rating}
        </li>
        <li>
          {restaurants[0].reviews[1].user}
          {restaurants[0].reviews[1].text}
          {restaurants[0].reviews[1].rating}
        </li>
      </ul>
    </div>
    <div>
      <h1>{restaurants[1].name}</h1>
      <h3>Меню</h3>
      <ul>
        <li>
          {restaurants[1].menu[0].name}
          {restaurants[1].menu[0].price}
          {restaurants[1].menu[0].ingredients}
        </li>
        <li>
          {restaurants[1].menu[1].name}
          {restaurants[1].menu[1].price}
          {restaurants[1].menu[1].ingredients}
        </li>
      </ul>
      <h3>Отзывы</h3><ul>
        <li>
          {restaurants[1].reviews[0].user}
          {restaurants[1].reviews[0].text}
          {restaurants[1].reviews[0].rating}
        </li>
        <li>
          {restaurants[1].reviews[1].user}
          {restaurants[1].reviews[1].text}
          {restaurants[1].reviews[1].rating}
        </li>
      </ul>
    </div>
    <div>
      <h1>{restaurants[2].name}</h1>
      <h3>Меню</h3>
      <ul>
        <li>
          {restaurants[2].menu[0].name}
          {restaurants[2].menu[0].price}
          {restaurants[2].menu[0].ingredients}
        </li>
        <li>
          {restaurants[2].menu[1].name}
          {restaurants[2].menu[1].price}
          {restaurants[2].menu[1].ingredients}
        </li>
        <li>
          {restaurants[2].menu[2].name}
          {restaurants[2].menu[2].price}
          {restaurants[2].menu[2].ingredients}
        </li>
      </ul>
      <h3>Отзывы</h3><ul>
        <li>
          {restaurants[2].reviews[0].user}
          {restaurants[2].reviews[0].text}
          {restaurants[2].reviews[0].rating}
        </li>
      </ul>
    </div>
    <div>
      <h1>{restaurants[3].name}</h1>
      <h3>Меню</h3>
      <ul>
        <li>
          {restaurants[3].menu[0].name}
          {restaurants[3].menu[0].price}
          {restaurants[3].menu[0].ingredients}
        </li>
        <li>
          {restaurants[3].menu[1].name}
          {restaurants[3].menu[1].price}
          {restaurants[3].menu[1].ingredients}
        </li>
      </ul>
      <h3>Отзывы</h3><ul>
        <li>
          {restaurants[3].reviews[0].user}
          {restaurants[3].reviews[0].text}
          {restaurants[3].reviews[0].rating}
        </li>
        <li>
          {restaurants[3].reviews[1].user}
          {restaurants[3].reviews[1].text}
          {restaurants[3].reviews[1].rating}
        </li>
      </ul>
    </div>
  </div>
);
